[dotenv@17.2.2] injecting env (5) from .env -- tip: ⚙️  suppress all logs with { quiet: true }
go model :  gpt-4o
error in model :  gpt-4o NotFoundError: 404 <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

    at Function.generate (/workspaces/tg-parser/node_modules/openai/src/core/error.ts:84:14)
    at OpenAI.makeStatusError (/workspaces/tg-parser/node_modules/openai/src/client.ts:463:28)
    at OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:713:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
  status: 404,
  headers: Headers {
    date: 'Tue, 07 Oct 2025 10:14:02 GMT',
    server: 'uvicorn',
    'content-type': 'text/html; charset=utf-8',
    'content-length': '207'
  },
  requestID: null,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
go model :  gpt-4.1
error in model :  gpt-4.1 NotFoundError: 404 <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

    at Function.generate (/workspaces/tg-parser/node_modules/openai/src/core/error.ts:84:14)
    at OpenAI.makeStatusError (/workspaces/tg-parser/node_modules/openai/src/client.ts:463:28)
    at OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:713:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
  status: 404,
  headers: Headers {
    date: 'Tue, 07 Oct 2025 10:14:02 GMT',
    server: 'uvicorn',
    'content-type': 'text/html; charset=utf-8',
    'content-length': '207'
  },
  requestID: null,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
go model :  gpt-4
error in model :  gpt-4 NotFoundError: 404 <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

    at Function.generate (/workspaces/tg-parser/node_modules/openai/src/core/error.ts:84:14)
    at OpenAI.makeStatusError (/workspaces/tg-parser/node_modules/openai/src/client.ts:463:28)
    at OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:713:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
  status: 404,
  headers: Headers {
    date: 'Tue, 07 Oct 2025 10:14:02 GMT',
    server: 'uvicorn',
    'content-type': 'text/html; charset=utf-8',
    'content-length': '207'
  },
  requestID: null,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
go model :  gpt-4o-mini
error in model :  gpt-4o-mini NotFoundError: 404 <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

    at Function.generate (/workspaces/tg-parser/node_modules/openai/src/core/error.ts:84:14)
    at OpenAI.makeStatusError (/workspaces/tg-parser/node_modules/openai/src/client.ts:463:28)
    at OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:713:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
  status: 404,
  headers: Headers {
    date: 'Tue, 07 Oct 2025 10:14:02 GMT',
    server: 'uvicorn',
    'content-type': 'text/html; charset=utf-8',
    'content-length': '207'
  },
  requestID: null,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
go model :  gpt-3.5-turbo
error in model :  gpt-3.5-turbo NotFoundError: 404 <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

    at Function.generate (/workspaces/tg-parser/node_modules/openai/src/core/error.ts:84:14)
    at OpenAI.makeStatusError (/workspaces/tg-parser/node_modules/openai/src/client.ts:463:28)
    at OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:713:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
  status: 404,
  headers: Headers {
    date: 'Tue, 07 Oct 2025 10:14:02 GMT',
    server: 'uvicorn',
    'content-type': 'text/html; charset=utf-8',
    'content-length': '207'
  },
  requestID: null,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
